# Generated by Django 3.1.2 on 2020-11-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sflightbook', '0002_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
