# Generated by Django 3.1.2 on 2020-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sflightbook', '0003_delete_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='flight',
            name='orgin',
            field=models.CharField(max_length=256),
        ),
    ]
