# Generated by Django 3.1.2 on 2020-11-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sflightbook', '0006_auto_20201104_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='orgin',
            field=models.CharField(max_length=256),
        ),
    ]
