# Generated by Django 3.1.2 on 2020-11-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sflightbook', '0009_auto_20201104_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('flight', models.ManyToManyField(blank=True, related_name='passsengers', to='sflightbook.Flight')),
            ],
        ),
    ]
