# Generated by Django 3.1.2 on 2020-11-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sflightbook', '0010_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='sflightbook.Flight'),
        ),
    ]
