# Generated by Django 3.1.2 on 2020-11-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sflightbook', '0012_airways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='sflightbook.airways'),
        ),
    ]
