# Generated by Django 3.1.2 on 2020-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
