# Generated by Django 3.1.2 on 2020-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsimple', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fruits',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
    ]
