# Generated by Django 3.1.2 on 2020-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiwarana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=2)),
                ('text', models.TextField()),
            ],
        ),
    ]
