# Generated by Django 3.1.2 on 2020-11-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaranatype', '0003_wiwarana_ansewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiwarana',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011')], max_length=4),
        ),
    ]
